#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "ERROR: This script must be run as root" 2>&1
  exit 1
fi

 interface=""
  host=github.com
  host_ip=$(getent ahosts "$host" | awk '{print $1; exit}')
  interface=`ip route get "$host_ip" | grep -Po '(?<=(dev )).*(?= src| proto)' | cut -f 1 -d " "`
  ip=$(/sbin/ip -f inet addr show $interface | grep -Po 'inet \K[\d.]+' | head -n 1)
  if [[ $ip == "" ]]; then
    # Never reply with a blank string - instead, use localhost if no IP is found
    # This would be the case if no network connection is non-existent
    ip="127.0.0.1"
  fi
# Install dialog

if [ $(dpkg-query -W -f='${Status}' wget 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
  dialog --infobox "Installing dialog" 3 34 ;
  if [[ $updated == 0 ]]; then
    apt-get update > /dev/null 2>&1
    updated=1
  fi
  apt-install -y install dialog > /dev/null 2>&1
fi  
if [ $(dpkg-query -W -f='${Status}' screen 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
  dialog --infobox "Installing screen..." 3 34 ;
  if [[ $updated == 0 ]]; then
    apt-get update > /dev/null 2>&1
    updated=1
  fi
  apt-get -y install screen > /dev/null 2>&1
fi

# Install WGET

if [ $(dpkg-query -W -f='${Status}' wget 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
  dialog --infobox "Installing wget..." 3 34 ;
  if [[ $updated == 0 ]]; then
    apt-get update > /dev/null 2>&1
    updated=1
  fi
  apt-get -y install wget > /dev/null 2>&1
fi

#Install Cron
if [ $(dpkg-query -W -f='${Status}' cron 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
  dialog --infobox "Installing cron..." 3 34 ;
  if [[ $updated == 0 ]]; then
    apt-get update > /dev/null 2>&1
    updated=1
  fi
  apt-get -y install cron > /dev/null 2>&1
fi

#Lets Install Minecraft
screen -S Minecraft-Server java -Xmx1024M -Xms1024M -jar server.jar nogui pause

sed -i "s/eula=false/eula=true/g" eula.txt

#####################################################
#
# Tweaking Server Configs
#####################################################

 # Enable Query
      # Change the value if it exists
      /bin/sed -i '/enable-query=/c\enable-query=true' server.properties
      # Add it if it doesn't exist
      if ! grep -q "enable-query=" server.properties; then
        echo "enable-query=true" >> server.properties
      fi

    # Set game difficulty to Normal (default is Easy, but we want at least SOME challenge)
      # Change the value if it exists
      /bin/sed -i '/difficulty=/c\difficulty=normal' server.properties
      # Add it if it doesn't exist
      if ! grep -q "difficulty=" server.properties; then
        echo "difficulty=normal" >> server.properties
      fi

  # Change the value if it exists
      /bin/sed -i '/view-distance=/c\view-distance=7' server.properties
      # Add it if it doesn't exist
      if ! grep -q "view-distance=" server.properties; then
        echo "view-distance=7" >> server.properties
      fi
  # Set motd
      # Change the value if it exists
      /bin/sed -i '/motd=/c\Dreamcraft Network's SMP' server.properties
      # Add it if it doesn't exist
      if ! grep -q "motd=A Minecraft Server" server.properties; then
        echo "motd=Dreamcraft Network's SMP" >> server.properties
      fi
