#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "ERROR: This script must be run as root" 2>&1
  exit 1
fi
# Install WGET

if [ $(dpkg-query -W -f='${Status}' curl 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
  dialog --infobox "Installing curl..." 3 34 ;
  if [[ $updated == 0 ]]; then
    apt-get update > /dev/null 2>&1
    updated=1
  fi
  apt-get -y install curl > /dev/null 2>&1
fi
# Install dialog

if [ $(dpkg-query -W -f='${Status}' wget 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
  dialog --infobox "Installing dialog" 3 34 ;
  if [[ $updated == 0 ]]; then
    apt-get update > /dev/null 2>&1
    updated=1
  fi
  apt-install -y install dialog > /dev/null 2>&1
fi  
if [ $(dpkg-query -W -f='${Status}' screen 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
  dialog --infobox "Installing screen..." 3 34 ;
  if [[ $updated == 0 ]]; then
    apt-get update > /dev/null 2>&1
    updated=1
  fi
  apt-get -y install screen > /dev/null 2>&1
fi

# Install WGET

if [ $(dpkg-query -W -f='${Status}' wget 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
  dialog --infobox "Installing wget..." 3 34 ;
  if [[ $updated == 0 ]]; then
    apt-get update > /dev/null 2>&1
    updated=1
  fi
  apt-get -y install wget > /dev/null 2>&1
fi

#Install Cron
if [ $(dpkg-query -W -f='${Status}' cron 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
  dialog --infobox "Installing cron..." 3 34 ;
  if [[ $updated == 0 ]]; then
    apt-get update > /dev/null 2>&1
    updated=1
  fi
  apt-get -y install cron > /dev/null 2>&1
fi
#welcome
dialog --msgbox "Thank You for installing Minecraft" 10 25

# Tweaking Server Configs
#####################################################

 # Enable Query
      # Change the value if it exists
      /bin/sed -i '/enable-query=/c\enable-query=true' server.properties
      # Add it if it doesn't exist
      if ! grep -q "enable-query=" server.properties; then
        echo "enable-query=true" >> server.properties
      fi

    # Set game difficulty to Normal (default is Easy, but we want at least SOME challenge)
      # Change the value if it exists
      /bin/sed -i '/difficulty=/c\difficulty=normal' server.properties
      # Add it if it doesn't exist
      if ! grep -q "difficulty=" server.properties; then
        echo "difficulty=normal" >> server.properties
      fi

  # Change the value if it exists
      /bin/sed -i '/view-distance=/c\view-distance=7' server.properties
      # Add it if it doesn't exist
      if ! grep -q "view-distance=" server.properties; then
        echo "view-distance=7" >> server.properties
      fi
  # Set motd
      # Change the value if it exists
      /bin/sed -i '/motd=/c\Dreamcraft Networks SMP' server.properties
 
 myip="$(dig +short myip.opendns.com @resolver1.opendns.com)"

 dialog --msgbox "Amount of RAM avaliable $(free -th)"  10 25

dialog --msgbox "Minecraft server runs on $ip Localhost." 10 25

dialog --msgbox "Minecraft Server runs on ${myip} Public host." 10 25

dialog --msgbox "This Installer Will restart twice Automatically." 10 25

dialog --msgbox "This is so that I can install all files the first time" 10 25

dialog --msgbox "then I can edit the config and other files the second time." 10 25

#Lets Install Minecraft
screen -S Minecraft-Server java -Xmx1024M -Xms1024M -jar server.jar nogui pause

sed -i "s/eula=false/eula=true/g" eula.txt

dialog --msgbox "EULA is now true. Please abide by Minecraft's EULA." 10 25

screen -S Minecraft-Server java -Xmx1024M -Xms1024M -jar server.jar nogui pause
#####################################################

dialog --msgbox "Thank You for installing Minecraft" 10 25

dialog --msgbox "Subscribe to Dreamcraft Network's Minecraft Youtube Channel." 10 25

dialog --msgbox "Check out minecraft.net if you have not obtained Minecraft." 10 25

dialog --msgbox "Documentation is here @ https://bit.ly/3QlIzsf" 10 25

dialog --msgbox "Join The Discord here @ https://dsc.gg/dreamcraft" 10 25

clear